# -*- coding: utf-8 -*-
"""Practice03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VqVqXIizbQCD5KZanZony4vNKWaE_rCF
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping, ModelCheckpoint
import os

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

# 실행할 때마다 같은 결과를 출력하기 위해 설정하는 부분입니다.
np.random.seed(3)
tf.random.set_seed(3)

# 데이터 입력
df = pd.read_csv('/content/drive/MyDrive/Deeplearning/deeplearning/dataset/iris.csv', names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"])

# 그래프로 확인
sns.pairplot(df, hue='species');
plt.show()

# 데이터 분류
dataset = df.values
X = dataset[:,0:4].astype(float)
Y_obj = dataset[:,4]

# 문자열을 숫자로 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)
Y_encoded = tf.keras.utils.to_categorical(Y)

# 학습 셋과 테스트 셋의 구분
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_encoded, test_size=0.4, random_state=0) #테스트셋 40 : 학습셋 60

# 모델의 설정
model = Sequential()
model.add(Dense(16,  input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

# 모델 컴파일
model.compile(loss='categorical_crossentropy',
            optimizer='adam',
            metrics=['categorical_accuracy'])

# 모델 저장 폴더 만들기
MODEL_DIR = '/content/drive/MyDrive/Deeplearning/deeplearning/model/testW09_3/'
if not os.path.exists(MODEL_DIR):
   os.mkdir(MODEL_DIR)

modelpath="/content/drive/MyDrive/Deeplearning/deeplearning/model/testW09_3/best_model.keras"

# 모델 업데이트 및 저장
checkpointer = ModelCheckpoint(filepath=modelpath, monitor='val_categorical_accuracy', verbose=1, save_best_only=True)

# 학습 자동 중단 설정
early_stopping_callback = EarlyStopping(monitor='val_categorical_accuracy', patience=10)
# 모델 실행
model.fit(X_train, Y_train, epochs=1000, batch_size=1, validation_data=(X_test, Y_test), callbacks = [early_stopping_callback, checkpointer], verbose=0)


# 결과 출력
print("\n Accuracy: %.4f" % (model.evaluate(X, Y_encoded)[1]))

#저장한 베스트 모델을 불러와서 성능 평가
from tensorflow.keras.models import load_model

best_model = load_model(modelpath)
error, acc = best_model.evaluate(X, Y_encoded, verbose=0) # 전체 데이터셋에 대해 다시 평가
print("Accuracy: %.4f" %acc)
print("Error: %.4f" %error)