# -*- coding: utf-8 -*-
"""Practice01-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8qvFrk2uKQCZvs-EYFVFs-P64kVe9lp
"""

# -*- coding: utf-8 -*-
# 코드 내부에 한글을 사용가능 하게 해주는 부분입니다.

import numpy
import pandas as pd
import tensorflow as tf
from numpy import array

from keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

numpy.random.seed(3)
tf.random.set_seed(3)

train_data = pd.read_csv('/content/drive/MyDrive/Deeplearning/week12/train_mydataset_6000.csv', header =0, names=['title', 'label'])
X_train = train_data['title']
Y_train = train_data['label']

test_data = pd.read_csv('/content/drive/MyDrive/Deeplearning/week12/test_mydataset_1500.csv', header = 0)
X_test = test_data['title']
Y_test = test_data['label']

print("첫번째 입력: ", X_train[0])
Y_train_onehot = to_categorical(Y_train)
Y_test_onehot = to_categorical(Y_test)
print("첫번째 one-hot 출력: ", Y_train_onehot[0])

#케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러 옵니다.
from tensorflow.keras.preprocessing.text import text_to_word_sequence


# 토큰화 함수를 이용해 전처리 하는 과정입니다.
token = Tokenizer()             # 토큰화 함수 지정
token.fit_on_texts(X_train)   # 토큰화 함수에 문장 적용
# print(token.word_index)
token_result = token.texts_to_sequences(X_train)
print(token_result[0])
train_len_max = max(len(l) for l in token_result)

print("학습셋 제목 최대 길이: %d" %train_len_max)
padded = pad_sequences(token_result, train_len_max)


#테스트셋 토큰화
token_test = Tokenizer()             # 토큰화 함수 지정
token_test.fit_on_texts(X_test)   # 토큰화 함수에 문장 적용
token_test_result = token.texts_to_sequences(X_test)
test_len_max = max(len(l) for l in token_test_result)

print("테스트셋 제목 최대 길이: %d" %test_len_max)
padded_test = pad_sequences(token_test_result, train_len_max)

print(padded[0])
word_size = len(token.word_index)+1
print(f"Word Size: {word_size}\n\n")


padded = numpy.array(padded, dtype='int32')
padded_test = numpy.array(padded_test, dtype='int32')

#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 8, input_length=14))
model.add(Flatten())
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(padded, Y_train_onehot, epochs=20)

print("\n Accuracy: %.4f" % (model.evaluate(padded_test, Y_test_onehot)[1]))