# -*- coding: utf-8 -*-
"""Practice02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12mi90BE5P7G5_0ckqtYl-KguS6CnXQkg
"""

import pandas as pd
import matplotlib.pyplot as plt

df1 = pd.read_csv('/content/drive/MyDrive/Deeplearning/week13/train_SectionDataset.csv', names=['title', 'section'], header=0)
print( df1.shape )
df1 = df1[df1['section'] == 0]
print(df1.shape)
print( df1.head(5) )

df2 = pd.read_csv('/content/drive/MyDrive/Deeplearning/week13/test_SectionDataset.csv', names=['title', 'section'], header=0)
df2 = df2[df2['section'] == 0]
print( df2.shape )
print(df2['title'][0])

new_string = df2['title'][0]
oneItem = {'title' : new_string, 'section' : 0}
df3 = pd.concat([df1, pd.DataFrame([oneItem])], ignore_index=True)
print(df3.shape)
print(df3.head(5))

from sklearn.feature_extraction.text import CountVectorizer

# print( df2[['genres']].head(3) )
count_vector = CountVectorizer( ngram_range=(1,3) )
c_vector_genres = count_vector.fit_transform( df3['title'] )
# print( c_vector_genres.shape )
# print( c_vector_genres[0] )
# print( "add1: ")
# print( c_vector_genres[0, 0:40] )
# print( "add2: ")
# print( c_vector_genres[0, 0], c_vector_genres[0, 1],  c_vector_genres[0, 33], c_vector_genres[0, 255])
# print( c_vector_genres[1, 0], c_vector_genres[1, 1],  c_vector_genres[1, 2])

from sklearn.metrics.pairwise import cosine_similarity

genres_c_sim = cosine_similarity( c_vector_genres )
print( genres_c_sim )

genres_c_sim = genres_c_sim.argsort()[:, ::-1]
print( genres_c_sim )

def get_recommend_movie_list(df, input_title, top=6):
    # 입력 제목 영화의 인텍스 값 추출
    target_index = df[ df['title'] == input_title].index.values
    print( target_index )
    # 코사인 유사도 중 비슷한 코사인 유사도를 가진 정보를 추출
    sim_index1 = genres_c_sim[target_index, :top]
    print( sim_index1 )
    sim_index2 = sim_index1.reshape(-1)
    print( sim_index2 )
    # 본인 제외
    sim_index3 = sim_index2[ sim_index2 != target_index ]
    print( sim_index3 )
    # 최종 선택
    return  df.iloc[ sim_index3 ]

get_recommend_movie_list( df3, new_string )

count_vector = CountVectorizer( ngram_range=(1,3) )
c_vector_genres = count_vector.fit_transform( df2['title'] )

genres_c_sim = cosine_similarity( c_vector_genres )
genres_c_sim = genres_c_sim.argsort()[:, ::-1]