# -*- coding: utf-8 -*-
"""Practice01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLoE2_u2fpb93d8kJlyMrWs5ecm_iJ9-
"""

import pandas as pd
import matplotlib.pyplot as plt

df1 = pd.read_csv('/content/drive/MyDrive/Deeplearning/week14/ratings.csv')
print( df1.shape )
print( df1.head(2) )

df2 = pd.read_csv('/content/drive/MyDrive/Deeplearning/week14/movies.csv')
print( df2.shape )
print( df2.head(2) )

df4 = pd.merge(df1, df2, on='movieId')
print( df4.shape )
print( df4.head(2) )

movie_user_rating = df4.pivot_table('rating', index='title', columns='userId')
print( movie_user_rating.shape )
print( movie_user_rating.head(3) )

new_rating = movie_user_rating.fillna(0)
print( new_rating.head(3) )

from sklearn.metrics.pairwise import cosine_similarity

item_collabor = cosine_similarity( new_rating )
print( item_collabor )

similarity_matrix = pd.DataFrame(data=item_collabor, index=new_rating.index, columns=new_rating.index)
print( similarity_matrix.head() )

def get_item_collabor(title):
    return similarity_matrix[title].sort_values(ascending=False)[:6]

print( get_item_collabor('Godfather, The (1972)') )

movie_user_rating = df4.pivot_table('rating', index='userId', columns='title')
new_rating = movie_user_rating.fillna(0)
item_collabor = cosine_similarity( new_rating )

similarity_matrix = pd.DataFrame(data=item_collabor,  index=new_rating.index, columns=new_rating.index )
print( similarity_matrix.head() )

def get_item_collabor(userId):
    return similarity_matrix[userId].sort_values(ascending=False)[:6]

print( get_item_collabor(3) )