# -*- coding: utf-8 -*-
"""Practice_11_3_1(RNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXfS-eyejhBc971AlbXBnDCkYAOybyzd
"""

# -*- coding: utf-8 -*-
# 코드 내부에 한글을 사용가능 하게 해주는 부분입니다.

import numpy
import pandas as pd
import tensorflow as tf
from numpy import array

from keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding
from keras.layers import LSTM

numpy.random.seed(2)
tf.random.set_seed(3)

train_data = pd.read_csv('/content/drive/MyDrive/Deeplearning/week13/train_SectionDataset.csv', header =0)
X_train = train_data['title']
Y_train = train_data['section']

test_data = pd.read_csv('/content/drive/MyDrive/Deeplearning/week13/test_SectionDataset.csv', header = 0)
X_test = test_data['title']
Y_test = test_data['section']

print("첫번째 학습셋 입력: ", X_train[0])
print("첫번째 테스트셋 입력: ", X_test[0])
Y_train_onehot = to_categorical(Y_train)
Y_test_onehot = to_categorical(Y_test)
print("첫번째 학습셋 one-hot 출력: ", Y_train_onehot[0])
print("첫번째 테스트셋 one-hot 출력: ", Y_test_onehot[0])

#케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러 옵니다.
from tensorflow.keras.preprocessing.text import text_to_word_sequence


# 토큰화 함수를 이용해 전처리 하는 과정입니다.
token = Tokenizer()             # 토큰화 함수 지정
token.fit_on_texts(X_train)   # 토큰화 함수에 문장 적용
token_result = token.texts_to_sequences(X_train)
train_len_max = max(len(l) for l in token_result)

print("\n학습셋 제목 최대 길이: %d" %train_len_max)
padded = pad_sequences(token_result, train_len_max)


#테스트셋 토큰화
token_test = Tokenizer()             # 토큰화 함수 지정
token_test.fit_on_texts(X_test)   # 토큰화 함수에 문장 적용
token_test_result = token.texts_to_sequences(X_test)
test_len_max = max(len(l) for l in token_test_result)

print("테스트셋 제목 최대 길이: %d" %test_len_max)
padded_test = pad_sequences(token_test_result, train_len_max)

word_size = len(token.word_index)+1
print(f"전체 데이터셋 단어 토큰 개수: {word_size}\n")

print("첫번째 학습셋 토큰 결과: " , token_result[0])
print("첫번째 테스트셋 토큰 결과: ", token_test_result[0])
print("\n첫번째 학습셋 패팅 토큰: ", padded[0])
print("첫번째 테스트셋 패팅 토큰: ", padded_test[0])


padded = numpy.array(padded, dtype='int32')
padded_test = numpy.array(padded_test, dtype='int32')

#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 8, input_length=train_len_max))
model.add(LSTM(55))
model.add(Dense(4, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(padded, Y_train_onehot, batch_size=100, epochs=5, validation_data=(padded_test, Y_test_onehot))

print("\n Accuracy: %.4f" % (model.evaluate(padded_test, Y_test_onehot)[1]))

import matplotlib.pyplot as plt

loss = history.history['loss']
val_loss = history.history['val_loss']

# 그래프로 표현
x_len = numpy.arange(len(loss))
plt.plot(x_len, loss, marker='.', c='blue', label='Trainset_loss')
plt.plot(x_len, val_loss, marker='.', c='red', label='Testset_loss')

plt.legend(loc='upper right')
plt.grid()
plt.xlabel('epoch')
plt.ylabel('loss')
plt.show()

for i in range(3):
  print(f"Index: {i}, 실제문장: {X_test[i]}")
  print(f"padded sequence: {padded_test[i]}")

  pred = model.predict(numpy.array([padded_test[i]]), verbose=0)
  print(f"예측결과: {pred}")
  print(f"Actual Section: {numpy.argmax(Y_test_onehot[i], -1)}, Expected Section: { numpy.argmax(pred) }")
  print("\n")