# -*- coding: utf-8 -*-
"""Practice02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XYEmlZPMe3Tum61jFKWFcnUDNWo71_JH
"""

import cv2
import math
import matplotlib.pyplot as plt
import pandas as pd
from keras.preprocessing import image
import numpy as np
import tensorflow as tf
from skimage.transform import resize
import os

os.makedirs("/content/drive/MyDrive/Deeplearning/week11(전이학습)/dataset/frames", exist_ok=True)
os.makedirs("/content/drive/MyDrive/Deeplearning/week11(전이학습)/model", exist_ok=True)

# 1초당 사진 추출(TRAIN)
count = 0
videoFile = "/content/drive/MyDrive/Deeplearning/week11(전이학습)/dataset/Tom and Jerry.mp4"
cap = cv2.VideoCapture(videoFile)
frameRate = cap.get(5)

x = 1
while(cap.isOpened()):
  frameId = cap.get(1) #현재 프레임 숫자
  ret, frame = cap.read()
  if(ret != True):
    break
  if(frameId % math.floor(frameRate) == 0):
    filename = "/content/drive/MyDrive/Deeplearning/week11(전이학습)/dataset/frames/frame%d.jpg" % count;count+=1
    cv2.imwrite(filename, frame)

cap.release()
print('Done!')

# 1초당 사진 추출(TEST)
count = 0
videoFile = "/content/drive/MyDrive/Deeplearning/week11(전이학습)/dataset/Tom and Jerry 3.mp4"
cap = cv2.VideoCapture(videoFile)
frameRate = cap.get(5)

x = 1
while(cap.isOpened()):
  frameId = cap.get(1) #현재 프레임 숫자
  ret, frame = cap.read()
  if(ret != True):
    break
  if(frameId % math.floor(frameRate) == 0):
    filename = "/content/drive/MyDrive/Deeplearning/week11(전이학습)/dataset/frames/test%d.jpg" % count;count+=1
    cv2.imwrite(filename, frame)

cap.release()
print('Done!')

# 사진 데이터 입력 및 크기 변경
data = pd.read_csv('/content/drive/MyDrive/Deeplearning/week11(전이학습)/dataset/mapping.csv') # 데이터 셋에 대한 라벨링
test = pd.read_csv('/content/drive/MyDrive/Deeplearning/week11(전이학습)/dataset/testing.csv') # 테스트 셋에 대한 라벨링

X = []
for img_name in data.Image_ID:
  img = plt.imread('/content/drive/MyDrive/Deeplearning/week11(전이학습)/dataset/frames/' + img_name)
  X.append(img)
X = np.array(X)

test_image = []
for img_name in test.Image_ID:
  img = plt.imread('/content/drive/MyDrive/Deeplearning/week11(전이학습)/dataset/frames/' + img_name)
  test_image.append(img)
test_img = np.array(test_image)

from keras.utils import to_categorical
train_y = to_categorical(data.Class)
test_y = to_categorical(test.Class)

image = []
for i in range(0, X.shape[0]):
  a = resize(X[i], preserve_range=True, output_shape=(224, 224, 3)).astype(int)
  image.append(a)
X = np.array(image)

test_image = []
for i in range(0, test_img.shape[0]):
  a = resize(test_img[i], preserve_range=True, output_shape=(224, 224, 3)).astype(int)
  test_image.append(a)
test_image = np.array(test_image)

#VGG16 기반 입력 사진 특성 추출

from sklearn.model_selection import train_test_split
X_train, X_vaild, y_train, y_vaild = train_test_split(X, train_y, test_size = 0.3, random_state = 42)

from keras.models import Sequential
from keras.applications import VGG16
from keras.layers import Dense, InputLayer, Dropout, Flatten

base_model = VGG16(weights = 'imagenet', include_top=False, input_shape=(224, 224, 3))

# X_train = base_model.predict(X_train)
# X_vaild = base_model.predict(X_vaild)
# test_image = base_model.predict(test_image)

# X_train = X_train.reshape(208, 7*7*512)
# X_vaild = X_vaild.reshape(90, 7*7*512)
# test_image = test_image.reshape(186, 7*7*512)

# train = X_train/X_train.max()
# X_vaild = X_vaild/X_vaild.max()
# test_image = test_image/test_image.max()
print('Done!!')

#VGG16 기반 자체 모델 생성

model = Sequential()
model.add(base_model)
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.summary()

from keras.callbacks import ModelCheckpoint, EarlyStopping
filepath='/content/drive/MyDrive/Deeplearning/week11(전이학습)/model/best_02.h5'
checkpoint = ModelCheckpoint(filepath, monitor = 'val_loss', verbose = 1, save_best_only=True, mode = 'min')
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10)

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
history = model.fit(X_train, y_train, epochs=100, validation_data=(X_vaild, y_vaild), callbacks=[early_stopping_callback, checkpoint])
print('Done2')

#생성모델 성능 평가
from keras.models import load_model
best_model = load_model('/content/drive/MyDrive/Deeplearning/week11(전이학습)/model/best_02.h5')

scores = model.evaluate(test_image, test_y)
print("Real Test %s; %.2F%%" %(model.metrics_names[1], scores[1]*100))

predictions = np.argmax(model.predict(test_image), axis = -1)
print("The screen time of None is ", predictions[predictions == 0].shape[0], "seconds")
print("The screen time of Jerry is ", predictions[predictions == 1].shape[0], "seconds")
print("The screen time of Tom is ", predictions[predictions == 2].shape[0], "seconds")

acc=history.history['accuracy']
val_acc= history.history['val_accuracy']
y_vloss = history.history['val_loss']
y_loss = history.history['loss']

x_len = np.arange(len(y_loss))
plt.plot(x_len, acc, marker='.', c='red', label='Trainset_acc')
plt.plot(x_len, val_acc, marker='.', c='lightcoral', label='Testset_acc')
plt.plot(x_len, y_vloss, marker='.', c='cornflowerblue', label='Testset_loss')
plt.plot(x_len, y_loss, marker='.', c='blue', label='Trainset_loss')

plt.legend(loc='upper right')
plt.grid()
plt.xlabel('epoch')
plt.ylabel('loss/acc')
plt.ylim(0, 2.0)
plt.show()